#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 41829-web-01 54.160.91.8:80 check\n\tserver 41829-web-02 54.164.167.128:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
